config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :pics do
    resources :comments, module: :pics
  end
  resources :comments, only: [ :destroy]
  devise_for :users
  root "pages#home"
  get "about" => "pages#about" #creates about_path
  get "miscellaneous" => "pages#miscellaneous"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :commentable, polymorphic: true
end

app/models/pic.rb
class Pic < ActiveRecord::Base
	belongs_to :user

	has_attached_file :image, 
										:styles => { :medium => "700x700", :thumb => "300x300"}

	validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
	validates :image, presence: true
	validates :description, presence: true

	has_many :comments, as: :commentable 
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_attached_file :image, :styles => {:medium => "700x700", :thumb => "300x300"}

	validates_attachment :image, content_type: {content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
	validates :image, presence: true
	validates :name, presence: true
	validates :description, presence: true

	has_many :comments, as: :commentable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :pics

   validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_comment, only: [:destroy]

	def create
		@comment = @commentable.comments.new comment_params
		@comment.user_id = current_user.id
		@comment.save
		redirect_to @commentable, notice: "Your comment was succesfully posted"
	end

	def destroy
    @comment.destroy
    redirect_to @commentable, notice: 'Comment was successfully deleted.' 
  end

	private 

		def comment_params
			params.require(:comment).permit(:body)
		end

		def set_comment
      @comment = Comment.find_by(id: params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	
  end
  
  def about
  end
end

app/controllers/pics/comments_controller.rb
class Pics::CommentsController < CommentsController
	before_action :set_commentable

	private

		def set_commentable
			@commentable = Pic.find(params[:pic_id])
		end

end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_action :set_pic, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @pics = Pic.all.order("created_at DESC").paginate(:page => params[:page], :per_page=> 15)
  end

  def show
  end

  def new
    @pic = current_user.pics.build
  end

  def edit
  end

 
  def create
    @pic = current_user.pics.build(pic_params)

    if @pic.save
      redirect_to @pic, notice: 'Pic was successfully created.'

    else
      render :new 
    end
  end

  def update
    if @pic.update(pic_params)
      redirect_to @pic, notice: 'Pic was successfully updated.' 
    else
      render :edit 
    end
  end


  def destroy
    if current_user.try(:admin?)
      @pic.destroy
      redirect_to pics_url, notice: 'Pic was successfully destroyed.' 
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pic
      @pic = Pic.find_by(id: params[:id])
    end

    def correct_user
      @pic = current_user.pics.find_by(id: params[:id])
      redirect_to pics_path, notice: "You don't have authorization to perform this action" if @pic.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pic_params
      params.require(:pic).permit(:description, :image)

    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :admin_user, only: [:new, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 15)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to @project, notice: 'Project was successfully created.' 
    else
      render :new 
    end
  end


  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.' 
    else
      render :edit 
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.' 
    format.json { head :no_content }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    def admin_user
      if !(current_user.try(:admin?))
        redirect_to projects_path, notice: "You don't have authorization to perform this action" 
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:description, :name, :image, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/_header.html.erb
	<%= csrf_meta_tag %> 
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%=link_to "Daniela Correa", root_path, class: "navbar-brand"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %> </li>
        <li><%= link_to 'About Me', about_path %> </li>
        <li><%= link_to pics_path do %>
          I <span class= "glyphicon glyphicon-heart"></span>
          <span class= "glyphicon glyphicon-cutlery"></span>
        <% end %></li>
        <li><%= link_to projects_path do %>
          <span class= "glyphicon glyphicon-console"></span>Projects
        <% end %></li>
        <li><%= link_to miscellaneous_path do %>
          Miscellaneous<span class= "glyphicon glyphicon-sunglasses"></span>Posts
        <% end %></li>

        <% if user_signed_in? %>
          <li>
            <%if current_user.admin? %>
              <%= link_to new_pic_path do %>
                <span class= "glyphicon glyphicon-plus"></span> New Pic
              <% end %>
              <%= link_to new_project_path do %>
                <span class= "glyphicon glyphicon-plus"></span> New Project
              <% end %>
            <%end%>
          </li>
          <li> <%= link_to 'Account Settings', edit_user_registration_path %> </li>
          <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %> </li>
        <% else %>
          <li><%= link_to 'Log In', new_user_session_path %> </li>
        <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyWebsite</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <!---for mobile devices use viewport -->
  <meta name= "viewport" content="width=device-width, initial-scale=1.0">  
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">

    <!--for each flash (messaged displayed once) do something -->
    <!--equals sign used to display things on the page-->
    <% flash.each do |name, msg|%> 
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/about.html.erb
<div class ="panel panel-default panel-transparent">
	
	<div class = "panel-heading center">
		 <h1>About me</h1> 
	</div>

	<div class= "panel-body">
		<p> Hi! I'm Daniela. I'm a computer science student at the University of British Columbia.<br>
		I'm building this webiste while learning Ruby on Rails, so many and constants changes will be happening to this site. I would like to give a big shout out to <%= link_to "OneMonth", "https://onemonth.com"%> and <%= link_to "GoRails", "https://gorails.com" %> for their extremely valuable resources and supportive community. <br>
		My main areas of interest: computer graphics, animation, machine learning and AI.<br>
		Little more about myself: <br>
		> I was born and raised in Durango, Mexico.<br>
		> I love dogs<br>
		> I take pictures of my food (no shame)<br>
		> I'm afraid of pigeons<br>
		> I have a love/hate relationship with programming and math which is what has kept me down this path<br>
		> I enjoy teaching and leaning<br>
		> Feminism is my Jam<br>
		Hope you guys enjoy navigating through this site (doesn't have much right now, I know I knoww..more coming soon). If you have any comments or wish to contact me you can message me (coming soon too..)<br>
		In case you were curious, background pictures were taken by <%= link_to "f93", "https://www.instagram.com/f93_/"%><br><br>

		Peace
		</p>
	 </div>
</div>

app/views/pages/home.html.erb
<div id='homepage' >

	<div class="jumbotron center">
		<h1>Food, Code & Sugar Skulls </h1>
		<p>
			Find me at 
			<%= link_to "https://github.com/Danielacoco", class:"btn btn-success btn-lg btn-github" do %>
				<span class="fa fa-github"></span>
			<% end %>
			<%= link_to "https://ca.linkedin.com/in/daniela-correa-orozco-437a94106", class:"btn btn-success btn-lg btn-linkedin" do%>
				<span class="fa fa-linkedin"></span>
			<% end %>
			<%= link_to	"https://www.instagram.com/danicorrea6/", class:"btn btn-success btn-lg btn-instagram" do %>
				<span class="fa fa-instagram"></span>
	  	<% end %>
			<%= link_to "https://twitter.com/Danicorrea6", class:"btn btn-success btn-lg btn-twitter" do %>
	     <span class="fa fa-twitter"></span>
	  	<% end %>
	  </a>
			</p>
		<% if user_signed_in? %>
			Welcome to my personal website </br> Enjoy your stay!!
		<% else %>
			<p> Comment or contact me by signing up! <%=link_to "Sign Up", new_user_registration_path, class:"btn btn-danger" %>
			</p>
		<% end %>
	</div class="jumbotron"> 
</div>

app/views/pages/miscellaneous.html.erb
<%= stylesheet_link_tag "miscellaneous" %>

app/views/pics/_comments.html.erb
<h3> Comments </h3>
<% @pic.comments.each do |comment| %>
	<div class = "well">
		<strong><%= User.find((comment.user_id)).username if comment.user_id? %></strong> <br>
		<%= comment.body %> <br>
		<div class= "actions" align = "right">
			<%= link_to raw('<span class= "glyphicon glyphicon-trash"></span>'),polymorphic_path([commentable, comment]), method: :delete if ((comment.user_id == current_user.id if comment.user_id?) || current_user.try(:admin?)) %>
		</div>
	</div>
<%end%>

app/views/pics/_form.html.erb
<%= form_for @pic, html: { multipart: true } do |f| %>
  <% if @pic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pic.errors.count, "error") %> prohibited this pic from being saved:</h2>

      <ul>
      <% @pic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-warning" %>
  </div>
<% end %>

app/views/pics/_formcomments.html.erb
<%= form_for [commentable, Comment.new] do |f| %>
	<div class ="form-group">
		<%=f.text_area :body, class: "form-control", placeholder: "Add a comment" %>
	</div>
	<%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/pics/edit.html.erb
<div class="panel panel-default">
	<div  class="panel panel-heading">
		<h1>Editing Pic</h1>
	</div>
	<div class= "panel-body">

		<%= render 'form' %>
	</div>
	<div class="panel-footer">
		<%= link_to 'Show', @pic %> |
		<%= link_to 'Back', pics_path %>
	</div>

</div>

app/views/pics/index.html.erb
<div id = "pics" class="transitions-enabled">
  <% @pics.each do |pic| %>
    <div class = "box panel panel-default panel-transparent">
      <%= link_to image_tag(pic.image.url(:thumb)), pic %>
      <div class="panel-body">
        <%= pic.description %> <br/>
        <% if current_user.try(:admin?) %>
          <div class= "actions" align = "right">
          <%= link_to raw('<span class= "glyphicon glyphicon-pencil"></span>'), edit_pic_path(pic) %>
          <%= link_to raw('<span class= "glyphicon glyphicon-trash"></span>'), pic, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        <%end%>
      </div>
    </div>
  <%end%>
</div>
<div class ="center">
<%= will_paginate @pics , renderer: BootstrapPagination::Rails %>
</div>

app/views/pics/new.html.erb
<div class="panel panel-default">
	<div  class="panel panel-heading">
		<h1>New Pic</h1>
	</div>
	<div class= "panel-body">
		<%= render 'form' %>
	</div>
	<div class="panel-footer">
		<%= link_to 'Back', pics_path %>
	</div>

</div>

app/views/pics/show.html.erb
<%= link_to 'Back', pics_path %>

<div class ="row">
	<div class = "col-md-offset-2 col-md-8">
		<div class= 'panel panel-default'>
			<div class = "panel-heading center">
				<%= image_tag @pic.image.url(:medium) %>
			</div>
			<div class = 'panel-body' align = 'center'>
				<p>
	  			<%= @pic.description %>
				</p>
				<p><strong> <%= @pic.user.username if @pic.user %></strong></p>

				<% if current_user.try(:admin?) %>
					<%= link_to 'Edit', edit_pic_path(@pic) %>
				<% end%>
			</div>
		</div>
	</div>
</div>

<%=render partial: 'pics/comments', locals: {commentable: @pic}%>
<%=render partial: 'pics/formcomments', locals: {commentable: @pic}%>

app/views/projects/_form.html.erb
<%= form_for @project, html: {multipart:true} do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :image%><br>
    <%= f.file_field :image, class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class = "form-group">
    <%= f.label :content %> <br>
    <%= f.text_area :content %>

 
  <div class="actions">
    <%= f.submit class: "btn btn-warning" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class = "center">
  <h1>Projects</h1>
</div>

<div id = "pics" class="transitions-enabled">
  <% @projects.each do |proj| %>
    <div class = "box panel panel-default panel transparent">
      <%= link_to image_tag(proj.image.url(:thumb)), proj %>
      <div class = "panel-body">
        <%=proj.name %> <br/>
        <%= proj.description %></br>
        <% if current_user.try(:admin?) %>
          <div class= "actions" align = "right">
            <%= link_to raw('<span class= "glyphicon glyphicon-pencil"></span>'),
            edit_project_path(proj) %>
            <%=link_to raw('<span class= "glyphicon glyphicon-trash"></span>'), proj, method: :delete, data: {confirm: 'Are you sure?'} %>
          </div>
        <%end%>
      </div>
    </div>
  <%end%>
</div>

<div class = "center">
<%= will_paginate @projects, renderer:
  BootstrapPagination::Rails %>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<%= link_to 'Back', projects_path%>

<div class = "row">
	<div class = "col-md-offset-2 col-md-8">
		<div class = "panel panel-default">
			<div class ="panel-heading center">
				<h1><%= @project.name %> </h1></br>
				<%= image_tag @project.image.url(:medium)%></br>
				<%= @project.description %>
			</div>
			<div class = "panel-body" align = "center">
				<p>
					<%= @project.content %>
				</p>
				<% if current_user.try (:admin?)%>
					<%= link_to 'Edit', edit_project_path(@project)%>
				<%end%>
			</div>
		</div>
	</div>
</div>